name: parentseye_parent
description: "A new Flutter project."
publish_to: "none"

version: 1.0.28+29

environment:
  sdk: ">=3.6.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  google_fonts: ^4.0.4
  font_awesome_flutter: ^10.5.0
  http: ^0.13.3
  url_launcher: ^6.3.1
  vector_math: ^2.1.4

  google_maps_flutter: ^2.9.0
  sliding_up_panel: ^2.0.0+1
  animations: ^2.0.8
 # share: ^2.0.4

  flutter_time_picker_spinner: ^2.0.0

  table_calendar: ^3.0.9
  syncfusion_flutter_charts: ^28.2.5+1
  flutter_svg: ^2.0.7
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.3.2
  loading_animation_widget: ^1.2.1
  provider: ^6.1.1
  geocoding: ^3.0.0
  flutter_local_notifications: ^18.0.1
  fluttertoast: ^8.2.4
  flutter_polyline_points: ^1.0.0
  flutter_dotenv: ^5.1.0
  gap: ^3.0.1
  flutter_google_places: ^0.3.0
  timeline_tile: ^2.0.0
  timezone: ^0.9.4
  dart_code_metrics: ^5.6.0
  google_nav_bar: ^5.0.6

  sqflite: ^2.3.3+1
  path: ^1.9.0
  web_socket_channel: ^3.0.2
  shimmer: ^3.0.0
  skeletons: ^0.0.3
  #workmanager: ^0.5.2
  local_auth: ^2.3.0
  pull_to_refresh: ^2.0.0
  firebase_core: ^2.20.0
  firebase_core_platform_interface: ^5.4.0
  firebase_analytics: ^10.6.0
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.2.7
  video_player: ^2.7.2
  flutter_tts: ^4.0.2
  package_info_plus: ^4.2.0
  socket_io_client: ^3.0.0
  in_app_update: ^4.2.3
  speech_to_text: ^7.0.0
  permission_handler: ^11.3.1
  smoothie: ^0.3.0+1
  app_settings: ^5.2.0
  firebase_messaging: ^14.7.10
  geolocator: ^13.0.2



dev_dependencies:
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
